version: '3.3'
services:
    nginx:
        container_name: nginx
        restart: always
        build:
            context: ./nginx
            dockerfile: Dockerfile
        volumes:
            - ${API}:/app/api
            - ${FRONT}:/app/front
            - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
            - ${NGINX_SITES_PATH}:/etc/nginx/conf.d
            - ./nginx/cors.conf.d:/etc/nginx/cors.conf.d
        ports:
            - "${NGINX_HOST_HTTP_PORT}:80"
            - "${NGINX_HOST_HTTPS_PORT}:443"
        links:
            - php-fpm
        networks:
            - app_network

    php-fpm:
        container_name: php-fpm
        restart: always
        build:
            context: ./php-fpm
            dockerfile: Dockerfile
        volumes:
            - ${API}:/app/api
        expose:
            - "9000"
        networks:
            - app_network

networks:
  app_network:
    driver: bridge
